networks:
  app_net:
    driver: bridge

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    env_file: ./.env.dev
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-dev
    restart: always
    env_file: ./.env.dev
    ports:
      - "5051:80"
    depends_on:
      - mysql-db
    networks:
      - app_net

  backend-dash:
    build:
      context: ./backend-dash
      dockerfile: Docker/Dockerfile.dev
      args:
        ENV: .env.dev
    container_name: backend-dash
    ports:
      - "3001:3000"
    depends_on:
      - mysql-db
    networks:
      - app_net

  backend-manager:
    build:
      context: ./backend-manager
      dockerfile: Docker/Dockerfile.dev
      args:
        ENV: .env.dev
    container_name: backend-manager
    ports:
      - "3002:3000"
    depends_on:
      - mysql-db
    networks:
      - app_net

  backend-site:
    build:
      context: ./backend-site
      dockerfile: Docker/Dockerfile.dev
      args:
        ENV: .env.dev
    container_name: backend-site
    ports:
      - "3003:3000"
    depends_on:
      - mysql-db
    networks:
      - app_net

  front-dash:
    build:
      context: ./front-dash/
      dockerfile: Docker/Dockerfile.dev
      args:
        ENV: .env.dev
    container_name: front-dash
    ports:
      - "3020:3000"
    volumes:
      - ./front-dash:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-dash
    networks:
      - app_net

  front-site:
    build:
      context: ./front-site
      dockerfile: Docker/Dockerfile.dev
      args:
        ENV: .env.dev
    container_name: front-site
    ports:
      - "3021:3000"
    volumes:
      - ./front-site:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend-site
    networks:
      - app_net

volumes:
  mysql-db-data:
