FROM node:23

# Cria diretório de trabalho
WORKDIR /app

# Copia apenas package.json e lock para cache de dependências
COPY package.json yarn.lock*

# Instala dependências
RUN yarn install

# Copia o restante da aplicação
COPY . .

# Copia o arquivo de variáveis de ambiente para o container
COPY .env.dev .env

# Expõe a porta padrão do Next.js
EXPOSE 3000

# Inicia o Next em modo dev (ideal para hot reload)
CMD ["yarn", "dev"]
